# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Haozhe Ji's Blog
author: Haozhe Ji
email: jhz16@mails.tsinghua.edu.cn
description: > # this means to ignore newlines until "baseurl:"
    exHFer/THU-EE/NLP enthusiast
#baseurl: "cdjhz.github.io" # the subpath of your site, e.g. /blog
url: "cdjhz.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  cdjhz

# Build settings
markdown: kramdown
#theme: minima
#plugins:
#  - jekyll-paginate
#pagniate: 5
#pagniate_path: "/pages:num/"

mathjax: true


plugins:
  - jekyll-paginate
paginate: 5
paginate_path: "/pages:num/"


excerpt_separator: <!-- more -->

permalink: /:categories/:title.html

social_media:
    github_url: https://github.com/cdjhz
    twitter_url: https://twitter.com/cdjhz
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
